apiVersion: app/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
selector:
  matchLabels:
    app: nginx
template:
  metadata:
    labels:
      apps: nginx
  spec:
    containers:
    - name: nginx
      image: nginx
    ports:
      containerPort: 80

